
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-content
  labels:
    Pour-Application: kuard
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: pacificproject-storage-policy
